// alert("Hello World");
// alert("Error! Please enter a valid password.");
// alert("Welcome to JS Land...\nHappy Coding!")

// alert("Welcome to JS Land...")
// alert("Happy Coding!")

// console.log("Hello...I can run JS through my web browser's console")

// chapter 2

// var username;

// var myName="Anas"

// var message="Hello World";
// alert(message);


// var name="Jhone Doe";
// var age="15 years old";
// var text="Certified Mobile Application Development"

// alert(name);
// alert(age);
// alert(text);


// var a="PIZZA\nPIZZ\nPIZ\nPI\nP";
// alert(a);

// var email="anasjaved358@gmail.com"
// alert("My email address is" +" " + email);

// var book="A smarter way to learn JavaScript";
// alert("I am trying to learn from the Book "+ " "+book)

// document.write("Yah!I can write HTML content through JavaScript")

// var b="▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
// alert(b);

// Chapter 3

// var age=15;
// alert("I am "+ age+" years old")

// var visit=14;
// alert("You have visited this site "+visit+ " times")

// var birthyear=1990;
// document.write("My birth year is " + birthyear + "<br>"); 
// document.write("Data type of my decleared variable is number");

// var Visitor_name="John Doe";
// var Product_title="T-Shirt";
// var Quantity=5;

// document.write(Visitor_name+" ordered "+Quantity+" "+ Product_title+"(s) on XYZ Clothing store");


// Chapter 4

// var a,b,c;

// var product_cost, Fname,   
// var P2_a%88$, product cost, A_good_grade_is_A+, @name;


// document.write("<h1>Rules for naming JS variables</h1>" +"<br>");
// document.write("Variable names can only contain,numbers $ or .For example $my_1stVariable"+"<br>");
// document.write("Variables must be begin with a letter.$ or For example $name, _name or name"+"<br>");
// document.write("Variable name are case sensitive"+"<br>");
// document.write("Variable names should not be JS keywords ")

// chapter 5

// var a=3;
// var b=5;
//  var c=a+b;
// var subtract=a-b;
// var multiply=a*b;
// var mod=a%b;
// document.write("Sum of "+ a +" and "+b+" is "+c);
// document.write("Subtraction of "+ a +" and "+b+" is "+ subtract);
// document.write("Multiplication of "+ a +" and "+b+" is "+ multiply);
// document.write("Modulus of "+ a +" and "+b+" is "+ mod);


// var a=5;
// document.write("Value after variable declaration is: "+a+ "<br>")
// document.write("Initial value is " +a +"<br>");

// a++;
// document.write("Value after increment is: " +a+"<br>");

// var a=a+7;
// document.write("Value after addition is: " +a+"<br>");
// --a;
// document.write("Value after decrement is: " +a+"<br>");

// document.write("The reminder is: 0");


// var ticket=600;
// var buy=5;
// var total= ticket*buy;

// document.write("Total cost to buy "+buy+" tickets to a movie is "+total+ " PKR")

// document.write("Table of 4" +"<br>")
// for(var i=1; i<=10;i++){
//     document.write("4"+" x "+i+" = "+ 4*i +"<br>");
// }


// var c=25;
// var F=70;

// var cel=(F-32)* 5/9;
// var fah=(c* 9/5)+32;

// document.write(c+" C is"+ fah+"F"+"<br>")
// document.write(F+" F is"+ cel+"C");

// var price1= 650;
// var price2= 100;
// var Quantity1=3;
// var Quantity2=7;
// var shippingchrges=100;

// document.write("<h2>Shopping Cart</h2>"+"<br>");
// document.write("Price of item 1 is "+price1+"<br>");
// document.write("Quantity of item 1 is "+Quantity1+"<br>")
// document.write("Price of item 2 is "+price2 +"<br>");
// document.write("Quantity of item 2 is "+Quantity2+"<br>");
// document.write("Total cost of your order is "+(price1*Quantity1 + price2*Quantity2 +shippingchrges));


// var totalMarks= 980;
// var marksObtain=804;

// document.write("<h2>Marks Sheet</h2>"+"<br>");
// document.write("Total marks: "+totalMarks+"<br>");
// document.write("Marks obtained: "+marksObtain+"<br>");
// document.write("Percentage: "+ (marksObtain/totalMarks*100));

// var dollars=10;
// var SaudiRiyal=25;

// document.write("Total Currency in PKR: "+ (dollars*104.80 + SaudiRiyal*28));

// var number=5;
// document.write("Add 5: "+ (number+5) +"<br>" + "Multiply by 10: "+number*10+"<br>" + "Divide by 2: " +number/2);


// var currentYear=2016;
// var birthyear=1992;
// document.write("<h2>Age Calculator </h2>"+"<br>");
// document.write("Current Year: "+currentYear+"<br>");
// document.write("Birth year: "+birthyear+"<br>");
// document.write("Your Age is: " +(currentYear-birthyear));

// var r=20;
// var circumference=125.67999999999999;

// document.write("<h2>The Geometrizer</h2>"+"<br>");
// document.write("Radius of a circle: "+r+"<br>");
// document.write("“The circumference: "+(2*3.142*r)+"<br>")
// document.write("The Area is: "+ (3.142*(r*r)));


// var favoriteSnack= "chocolate chip";
// var currentAge=15;
// var maxAge=65;
// var amount=3;

// document.write("<h2>The Lifetime Supply Calculator</h2>"+"<br>");
// document.write("Favorite Snack: "+favoriteSnack+"<br>");
// document.write("Current Age: "+ currentAge +"<br>");
// document.write("Amount of snakes per day: "+amount+"<br>")
// document.write("You will need "+(currentAge*10) +" to last you until the ripe old age of "+ maxAge)



// chapter 6 to 9

// var a=10;

// document.write("<h2>Result</h2><br>")
// document.write("The value of a is: "+a+"<br>");
// document.write("......................................"+"<br>")
// document.write("<br>");
// document.write("The value of  ++a is: "+ ++a+"<br>");
// document.write("Now the value of a is: "+a+"<br>");
// document.write("<br>");
// document.write("<br>");
// document.write("The value of a++ is: "+ a++ +"<br>");
// document.write("Now the value of a is: "+a+"<br>");
// document.write("<br>");
// document.write("<br>");
// document.write("The value of --a is: "+ --a +"<br>");
// document.write("Now the value of a is: "+a+"<br>");
// document.write("<br>");
// document.write("<br>");
// document.write("The value of a-- is: "+ a-- +"<br>");
// document.write("Now the value of a is: "+a+"<br>");


// var a=2;
// var b=1;
// var result= --a - --b + ++b + b--;

// document.write("a is: "+a+"<br>");
// document.write("b is: "+b+"<br>")
// document.write("Result: "+result)


// var person = prompt("Please enter your name");
// alert("Hello! Hope you fine ")

// var num = prompt("Enter Number", "0") 
// var num = parseInt(num);
// var i = 0;
// document.write('<table border="1" cellspacing="0">');
// for (i = 1; i <= 10; i++) {
//   document.write("<tr><td>" + num + " x " + i + " = " + num * i + "</td></tr>");
// }


// var eng=100;
// var math=100;
// var urdu=100;
// var englishObtainedmarks= parseInt (prompt ("Enter English Marks"));
// var mathObtainedmarks=parseInt(prompt("Enter Maths Marks"));
// var urduObtainedmarks=parseInt(prompt("Enter Urdu Marks"));
// var totalObtainMarks=englishObtainedmarks+ mathObtainedmarks+urduObtainedmarks;
// var engPerc=(englishObtainedmarks/eng*100);
// var UrduPercent=(urduObtainedmarks/urdu*100);
// var mathpercent=(mathObtainedmarks/math*100);
// var totalPercent=((engPerc+UrduPercent+mathpercent)/3);
// document.write('<table border="0" cellspacing="0" cellpadding="1">');
// document.write("<tr><td><h4>Subect </h4></td>"+"<td><h4>Total marks </h4> </td>"+"<td><h4>Obtain Marks</h4> </td>"+"<td><h4>Percentage</h4></td></tr>");
// document.write("<tr><td>English  </td>"+ "<td> 100 </td>"+"<td>"+englishObtainedmarks +"</td>"+"<td>" +engPerc+"%</td></tr>");
// document.write("<tr><td>Maths  </td>"+ "<td> 100 </td>"+"<td>"+mathObtainedmarks+"</td>"+"<td>" +mathpercent+"%</td></tr>");
// document.write("<tr><td>Urdu  </td>"+ "<td> 100 </td>"+"<td>"+ urduObtainedmarks +"</td>"+"<td>" +UrduPercent+" %</td></tr>");
// document.write("<tr><td></td>"+"<td> <h4>"+(eng+urdu+math)+"</h4></td>" +"<td><h4>"+totalObtainMarks+"<h4></td>"+"</td>"+"<td><h4>"+totalPercent+" %<h4></td></tr>")




// CHAPTER NO 9 to 11


// var city= prompt("Enter your City");
// if(city="karachi"){
//     alert("Welcome to city of lights")
// }

// var gender= prompt("Enter your Gender");
// if(gender=== "male"){
//     alert("Good Morning Sir.")
// }
//  if(gender==="female"){
//     alert("Good Morning Ma’am.")
// }


// var color=prompt("Enter color");
// if(color==="red"){
//     alert("Must Stop.")
// }
// else if(color==="yellow"){
//     alert("Ready to go.")
// }
// else if(color==="green"){
//     alert("Move now")
// }

// var fuel=parseInt(prompt("Enter remaining fuel in car"));
// if(fuel<0.25){
//     alert("Please refill the fuel in your car")
// }

//  var a = 4;
// if (++a === 5){
// alert("given condition for variable a is true");
// }

// output: given condition for variable a is true

// var b = 82;
// if (b++ === 83){
// alert("given condition for variable b is true");
// }

// output:: error in program bcoz b=82   condition for variable b is false

// var c = 12;
// if (c++ === 13){
// // alert("condition 1 is true");  not true bcoz c=12
// }
// if (c === 13){
// alert("condition 2 is true"); now c=13 
// }
// if (++c < 14){
// alert("condition 3 is true");  its false bcox c=14
// }
// if(c === 14){
// alert("condition 4 is true"); true condition bcoz c=14
// }


// var materialCost = 20000;
// var laborCost = 2000;
// var totalCost = materialCost + laborCost;
// if (totalCost === laborCost + materialCost){
// alert("The cost equals");
// }


// condition is true bcox total cost=22000


// if (true){
//     alert("True");
//     }
//     if (false){
//     alert("False");
//     }
// condition is true in first if statement thats why second statmnt not run


// if("car" < "cat"){
//     alert("car is smaller than cat");
//     }


// var eng=100;
// var math=100;
// var urdu=100;
// var englishObtainedmarks= parseInt (prompt ("Enter English Marks"));
// var mathObtainedmarks=parseInt(prompt("Enter Maths Marks"));
// var urduObtainedmarks=parseInt(prompt("Enter Urdu Marks"));
// var totalObtainMarks=englishObtainedmarks+ mathObtainedmarks+urduObtainedmarks;
// var engPerc=(englishObtainedmarks/eng*100);
// var UrduPercent=(urduObtainedmarks/urdu*100);
// var mathpercent=(mathObtainedmarks/math*100);
// var totalPercent=((engPerc+UrduPercent+mathpercent)/3);
// var total=eng+math+urdu;
// document.write("<h3>Marks Sheet</h3><br>")
// document.write("Total Marks: "+ total+"<br>");
// document.write("Marks Obtained: "+totalObtainMarks+"<br>")
// document.write("Percentage: "+totalPercent+"<br>")

// if(totalPercent>=80){
//     document.write("Grade: A-one"+"<br>")
//     document.write("Remarks: Excellent")
// }
// else if(totalPercent>=70){
//     document.write("Grade: A"+"<br>")
//     document.write("Remarks: Good")
// }
// else if(totalPercent>=60){
//     document.write("Grade: B"+"<br>")
//     document.write("Remarks: You need to improve")
// }
// else if(totalPercent<60)
// {
//     document.write("Grade: Fail"+"<br>")
//     document.write("Remarks: Sorry")
// }

// var number=parseInt (prompt("Enter any number"));
// if(number <=10){
//     alert("Correct answer")
// }
// else if(number<=11)
// {alert("Close enough to the correct answer")
// }


// var num= prompt("Enter number")

// if(num%3==0){

//     alert("Number is divisible by 3")
// }
// else
// {
//     alert("Number is not divisible by 3")
// }


// var num= prompt("Enter number")
// if(num%2==0){
//     alert("Its even number")
// }
// else
// {
//     alert("Its Odd number")
// }


// var temp=prompt("Enter Temperature")
// if(temp>40){
//     alert("It is too hot outside.")
// }
// else  if(temp>30){
//     alert("The Weather today is Normal.")
// }
// else if(temp>20){
//     alert("Today’s Weather is cool.")
// }
// else if(temp>10)
// {
//     alert("OMG! Today’s weather is so Cool.")
// }

// var a= parseInt(prompt("Enter 1st value "));
// var b= parseInt(prompt("Enter 2nd value "));
// var c=prompt("Enter operator","+ , -, x , /,%")

// if(c==="+"){
//     alert(a+b);
// }
// else if(c==="-"){
//     alert(a-b);
// }
// else if(c==="x"){
//     alert(a*b);
// }
// else if(c==="/"){
//     alert(a/b);
// }
// else if(c==="%"){
//     alert(a%b);
// }
// else{
//     alert("You entered Wrong operator")
// }

// // CHAPTER NO 12 to 13

// var num = parseInt(prompt("Enter value"))

// if ((num >= 65 && num <= 90)  || (num >= 97 && num <= 122)) {
//             alert("It is an Alphabet")
//         }
//         else if (num>= 48 && num <= 57) 
//         {
//             alert("It is Digit")
//         }
       


// var a= parseInt(prompt("Enter 1st value "));
// var b= parseInt(prompt("Enter 2nd value "));
// if(a>b){
//     alert("1st  value is larger ")
// }
// else if(a<b){
//     alert("2nd  value is larger ")
// }
//  else if(a=b){
//     alert("Both values are Equal ")
// }


// const number = parseInt(prompt("Enter a number: "));


// if (number > 0) {
//   alert("The number is positive");
// }
// else if (number == 0) {
//   alert("The number is zero");
// }
// else {
//     alert("The number is negative");
// }


// var x = prompt("Enter a character ");
// if(x === "A" || x === "E" || x === "I" || x === "O" || x === "U" ) {
//     alert("It is a vowel,")
// }
// else if(x === "a" || x === "e" || x === "i" || x === "o" || x === "u"){
//     alert("It is a vowel,")
// }
// else{
//     alert("It is not a vowel,")
// }


// var password="anasjaved";
// var p=prompt("Enter password");
// if( p===""){
//     alert(" Please enter your password")
// }
// else if(p===password){
//     alert("Correct! The password you entered matches the original password.")
// }
// else{
//     alert("Incorrect password")
// }


// var greeting;
// var hour = 13;
// if (hour < 18) {
// greeting = "Good day";
// alert(greeting)
// }
// else{
// greeting = "Good evening";
// alert(greeting)
// }


// var time=prompt("Enter time","Time in 24 format")
// if(time>=0000 && time<1200){
//     alert("Good Morning.")
// }
// else if(time>=1200 && time<1700){
//     alert("Good Afternoon.")
// }
// else if(time>1700 && time<2100)
// {
//     alert("Good Evening.")
// }
// else if(time>=2100 && time<=2359)
// {
//     alert("Good Night.")
// }


//CHAPTER 14 to 16

// var objectA = {}
// var objectB = new Object()


// var cars = ["Saad", "Anas", "Talha"];

// var num=[5,4,5,10,20]

// var booleanArray = [true, false, false, true];


// var mixedArray = [1, "two", "three", 4];

// var arr=["SSC","HSC","BCS","BS","BCOM","MS","M.PHIL","PhD"]

// document.write("<h2>Qualification</h2><br>")
// document.write(arr[0]+"<br>")
// document.write(arr[1]+"<br>")
// document.write(arr[2]+"<br>")
// document.write(arr[3]+"<br>")
// document.write(arr[4]+"<br>")
// document.write(arr[5]+"<br>")
// document.write(arr[6]+"<br>")
// document.write(arr[7])

// var std=["Michael","John","Tony"];
// var marks=[320,230,480]



// document.write("Score of "+std[0]+" is "+marks[0]+"Percentage  "+(marks[0]/500*100) +" %.<br>");
// document.write("Score of "+std[1]+" is "+marks[1]+"Percentage "+(marks[1]/500*100)+" %.<br>");
// document.write("Score of "+std[2]+" is "+marks[2]+"Percentage "+(marks[2]/500*100)+" %.<br>");


// var color=["Red " ,"Green ","Yellow "]
// document.write(color+"<br>");
// document.write("........................................................"+"<br>")
// document.write("<br>")
// color.unshift("Pink");
// document.write("Updated Array After Adding in Beginning  <br>")
// document.write("<br>")
// document.write(color+"<br>");
// document.write("<br>")
// document.write("..........................................................."+"<br>")
// document.write("<br>")
// document.write("Updated Array After Adding in end  <br>")
// document.write("<br>")
// color.push("Purrple")
// document.write(color+"<br>");
// document.write("<br>")
// document.write("..........................................................."+"<br>")
// color.unshift("Grey","White");
// document.write("Updated Array After Adding 2 colors in Beginning  <br>")
// document.write("<br>")
// document.write(color+"<br>");
// document.write("..........................................................."+"<br>")
// color.shift();
// document.write("Updated Array After delete 1st color in Beginning  <br>")
// document.write("<br>")
// document.write(color+"<br>");

// document.write("..........................................................."+"<br>")
// color.splice(4,5);
// document.write("Updated Array After delete last 2 color  <br>")
// document.write("<br>")
// document.write(color+"<br>");

// var std=[320,230,480,120]

// document.write("Score of Students: "+std)
// document.write("Score of Students: "+ass std)


// eggsInNest.sort();

// // e.g.: [109, 136, 156, 188, 19, 190, 2, 34, 55, 90]

// var points = [40, 100, 1, 5, 25, 10];
// document.getElementById("demo").innerHTML = points;

// function myFunction() {
//   points.sort(function(a, b){return a-b});
//   document.getElementById("demo").innerHTML = points;
// }


// CHApter 17 to 20


// var Arr=[[1,2],[3,4],[5,6]];

// var Arr=[[0,1,2,3],
// [1,0,1,2],
// [2,1,0,1]];
// document.write(Arr)


// for(var i=1;i<=10;i++){
//     document.write(i+"<br>");
// }

// var num=prompt("Enter a number to show its multiplication table")
// var count=prompt("Enter lenght multiplication table")
// for(var i=1;i<=count;i++)
// {
//     document.write(num + " x "+i+" = "+i*num +"<br>")
// }

// var array=["apple", "banana","mango", "orange",  "strawberry"]
// document.write(array[0]+"<br>");
// document.write(array[1]+"<br>");
// document.write(array[2]+"<br>");
// document.write(array[3]+"<br>");
// document.write(array[4]+"<br>");


// document.write("Elemenet in index 0 is "+array[0]+"<br>");
// document.write("Elemenet in index 1 is "+array[1]+"<br>");
// document.write("Elemenet in index 2 is "+array[2]+"<br>");
// document.write("Elemenet in index 3 is "+array[3]+"<br>");
// document.write("Elemenet in index 4 is "+array[4]+"<br>");

// document.write("<h4>Counting</h4><br>")
// document.write("1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15<br>")
// document.write("<h4>Reverse Counting</h4><br>")
// document.write("10, 9, 8, 7, 6, 5, 4, 3, 2, 1<br>")
// document.write("<h4>Even</h4><br>")
// document.write("0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20<br>")
// document.write("<h4>Odd</h4><br>")
// document.write("1, 3, 5, 7, 9, 11, 13, 15, 17, 19<br>")
// document.write("<h4>Series</h4><br>")
// document.write("2k, 4k, 6k, 8k, 10k, 12k, 14k, 16k, 18k, 20k<br>")


// var A=[ "cake","apple pie","cookie","chips","patties"]
// var input=prompt("search by user input");

// if(A.indexOf(input) !== -1){
//     document.write(input+" is Avalaible at index "+A.indexOf(input)+" in our bakery ")
// }
// else{
//     document.write("We are sorry! "+input +" is Not avalaible")
// }


var arr = [24,53,78,91,12];
var largest = arr[0];

for (var i = 0; i < arr.length; i++) {
    if (largest < arr[i] ) {
        largest = arr[i];
    }
}

document.write("<h4>Array items: </h4>"+arr);
document.write("<h4>The largest number is: "+largest)


var arr = [24,53,78,91,12];
var smallest = arr[0];

for (var i = 0; i < arr.length; i++) {
    if (smallest > arr[i] ) {
        smallest = arr[i];
    }
}

document.write("<h4>Array items: </h4>"+arr);
document.write("<h4>The smallest number is: "+smallest)


// for(var i=5;i<20;i+5){
//     document.write(i+"<br>");
// }